name: Deploy-to-EC2

# Trigger deployment only on push to dev branch
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.USERNAME }}
          port: 22

          script: |
            cd /var/www/staging/writeHouseBackend
            sudo git checkout dev 
            sudo git add .
            sudo git reset --hard origin/dev
            git pull origin dev
            sudo yarn
            sudo yarn migrate:run
            NODE_OPTIONS=--max_old_space_size=1024 sudo yarn pm2:deploy:staging
